### ISSUE TITLE
Remove from Google Fonts: Font is riddled with so many issues with no sign of fixes or active development

### ISSUE THREAD

**Issue by patrickjane12** [tokotype/PlusJakartaSans#30] opened 2022-07-27 04:21 UTC
The font does not deserve to be on Google Fonts. It doesn't get basics right and is riddled with so many bugs. There is no sign of any active development. There's just replies to the issues with no fixes at all. 

The last update was in Nov 2021 i.e. 8 months ago. If you don't intend to maintain the fonts or at least fix so many basic issues that make this font unusable, remove them from Google Fonts and help all of us out not to waste time on checking out a bug ridden product.

Just look at issues where it doesn't even get some core/basic features right: Issues #9, #19, #25 #27, #28

**Comment by nrthbound** [comment] 2022-09-29 19:28
Since it's an open-source font, how about you make some adjustments and contribute them instead of whining about people using their free time to develop what is, without a doubt, the BEST Circular alternative on the web. You can go pay $4k to use Circular, or you can contribute some fixes to this font. Your obnoxiously rude and entitled attitude have no business here.

**Comment by patrickjane12** [comment] 2022-09-30 04:22
@nrthbound No need to get so personal and butthurt. My point was simple: the authors shouldn't make this font seem production ready by keeping it in the Google Fonts collection. I have used a lot of fonts on Google Fonts and these are by far the most buggy and ill-maintained.

Also, the issue here serves as a warning to other users wanting to try these fonts out where the basics aren't working as expected and core issues have just remained open since November 2021.

I understand open source work is valuable but getting butthurt over a genuine criticism is being a touch lot. Brutal honesty and transparency is more important in open source.

**Comment by nrthbound** [comment] 2022-09-30 05:19
@patrickjane12 Not "butt hurt" at all (Someone really wants to appear "edgy", not to mention your first comment is riddled with crybaby diatribes). But it's a simple fact, if you don't like it, take a hike. They don't owe you a damn thing. It's an open source project, which means you or anyone else can fix their own issues with it. But you come here, crying like a baby with this high-and-mighty Karen attitude? You're one of those wankers who whines about everything every time you go to a restaurant aren't you? "My water has too much ice!" "This is medium-rare, I wanted medium-medium rare!" Oh, and I've been using the font just fine... Maybe you should learn how to work past simple issues until the developers decide to fix them? Or, if they're not going to (which they have no obligation to do), fix it yourself. I guess crying is easier than learning, even though the workaround is posted in another issue. However, if that's how you act towards folks who gave us a great font for free? Eh, no one likes a spoiled brat.

**Comment by kenmcd** [comment] 2022-10-01 21:20
> Just look at issues where it doesn't even get some core/basic features right: Issues #9, #19, #25 #27, #28

Ignorance and cluelessness on display.

**The Stem of Letter "k" Goes Above the Cap Height #9** 
It is quite common for some lowercase characters to extend above the caps height. If you look a little closer you will see the b, d, k, and l all exceed the caps height. Like lots of fonts.
That issue should be closed.
The poster is just ignorant about a common font design choice.

**some composite emojis does not render correctly #19** 
Clearly you did not even read the issue. 
It is about characters which do not exist in the fonts.
Just clueless.
That issue should be closed.

**Spacing between words #25** 
That is a design choice not a flaw.
I like the spacing.
Just because some other fonts may have excessive spacing does not mean there is something wrong here.
You like space rivers in your text, use another font.

**The letters F and I have problems when they become words #27** 
The poster does not know what standard ligatures are.
Do you? 
Either you did not actually read the "issue" again, or you are as clueless as the poster.
That non-issue should be closed.

**Font isn't vertically centered (Some empty space remains at the top of the text) #28** 
You will find this issue in many other font repositories.
Lots of issues with how browsers render text vertically in tight spaces - and the browsers all do it differently.
Vertical metrics best for desktop use may not be the best for use in a browser.
This is the fault of the CSS and the browsers, not the font.
There are multiple work-arounds posted online.
And there are some proposals to the next CSS standards to deal with this issue where it should be - in the CSS/browser.
The problem is not the fonts.

So all of your supposed major issues are clueless nonsense.

This "issue" should be closed as _poster is clueless, nothing to fix._

**Comment by patrickjane12** [comment] 2022-10-02 04:03
@kenmcd You may be right about certain stuff. But I find you even more ignorant and just being defensive for the sake of it.

1. Emojis not rendering are NOT an issue with any Google fonts I have tried. This is the only one. 
2. Did you even read the last issue? It isn't  even about browsers 🤦‍♂. It is about using it in   Android/iOS apps.

The whole point of this issue is none of the other Google Fonts have these kind of issues at all. Get the point of the issue now?

**Comment by wpbft** [comment] 2022-10-13 07:56
> @kenmcd You may be right about certain stuff. But I find you even more ignorant and just being defensive for the sake of it.
> 
> 1. Emojis not rendering are NOT an issue with any Google fonts I have tried. This is the only one.
> 2. Did you even read the last issue? It isn't  even about browsers 🤦‍♂. It is about using it in   Android/iOS apps. The vertical alignment issue makes the font totally unusable on mobile OS.
> 
> The whole point of this issue is none of the other Google Fonts have these kind of issues at all. Submitting these fonts to Google Fonts seems heavily premature. Get the point of the issue now?

I'm sure your "enthusiasm" is coming from that you actually like the font. Being rude will only take you so far. If you can't use the font, choose another one. Let's keep in mind there are people on the other side of the screen. Keep patience, contribute and if you can't - stay away.

**Comment by patrickjane12** [comment] 2022-10-13 10:54
@wpbft Sure, I do like the font despite the fact that I feel that this font shouldn't be a part of Google fonts at this time. They should be removed until the contributors or authors are able to fix the existing issues that make the font unusable for production use in apps or websites.

I just hope that the stakeholders take note of valid criticism. I rest my case. If the authors have a response, they can comment it over here and close this issue if they need to.

**Comment by wpbft** [comment] 2022-10-13 19:20
There are many of us who are more than fine using this font in production. A site like Pexels.com, with 30 million+ visits, is using it. As you can see there are nobody here that agrees with you, and that is because you're being a jerk and exaggerate the importance of the problems - or simply being incompetent and unable to overcome these issues. Go educate yourself.

**Comment by patrickjane12** [comment] 2022-10-13 20:50
@wpbft Kindly shut up if you haven't read or are fully incapable of understanding the point of the issue. At this point you're acting like an bumbling jerk yourself. 

Most people shy away from criticism like this. It is already been said, Noone needs to come around like kids here just to say 'Agreed' 'Me too'. It's always the super-sensitive people come around to defend the indefensible. Do you expect ALL your users to be experts in font design/development tools? Jesus. It's such a stupid advice to say contribute ir shut up and stop providing feedback.

**Comment by wpbft** [comment] 2022-10-13 21:00
I'm fully able to understand the point of issue. The point of issue is you. I'm not an expert in font design or development tools, but as most other people here, I have manners. You, on the other hand, don't possess anything required to be here. You don't have manners, you have no competence and you have no clue about what to expect from open source projects. You have absolutely nothing to contribute except toxic nonsense. I'm now the third person to point it out. One have to wonder have many more you need.

**Comment by patrickjane12** [comment] 2022-10-13 21:29
@wpbft Again, I do not argue with peasants. When/

These are the cold facts:
1. These fonts cannot be used on mobile devices at this time due to the alignment issue. Tested on both iOS and Android. 
2. There have been zero updates on the any recent reported issues and no fixes since, November 2021, a very long time. 

I've already made my points and have left it to the authors to close this issue if they want to. No need for cry babies to come running over here. Save your time.

**Comment by wpbft** [comment] 2022-10-13 21:47
@patrickjane12 One of the best ways to spot a crybaby is to identify the lack of ability to keep patience.

A baby will never understand why it has to wait, and therefore cries to get what it wants. 

Over time and with parents guidance, it will develop language and other social skills to achieve what it wants in more efficient ways.

**Comment by patrickjane12** [comment] 2022-10-13 21:50
@wpbft The universe face palms as it sees the point going miles above your head.

**Comment by akhmadilham** [comment] 2023-01-23 07:42
> @wpbft The universe face palms as it sees the point going miles above your head.

Hahaha, your statement may be valid and u ain't contribute anything to this font even if you been seen problems with it. 🤪 Doing design masturbation on open source font, using the edgy word to look sounds powerful. Why do you even spend time doing this lengthy critique kiddo 🤪

**Comment by akhmadilham** [comment] 2023-01-23 08:06
> @wpbft The universe face palms as it sees the point going miles above your head.



> @wpbft Again, I do not argue with peasants.
> 
> These are the cold facts:
> 
> 1. These fonts cannot be used on mobile devices at this time due to the alignment issue. Tested on both iOS and Android.
> 2. There have been zero updates on the any recent reported issues and no fixes since, November 2021, a very long time. I'm not saying they're on clock here. But at least pin an issue about the status of the maintainers. Whether they are no longer active, need more maintainers, or consider archiving the repo, etc.
> 
> I've already made my points and have left it to the authors to close this issue if they want to. No need for cry babies to come running over here. Save your time.

Hahaha, your statement may be valid and u ain't contribute anything to this font even if you been seen problems with it. 🤪 Doing design masturbation on open source font, using the edgy word to look sounds powerful. Why do you even spend time doing this lengthy critique kiddo 🤪

**Comment by akhmadilham** [comment] 2023-01-23 08:07
@patrickjane12 
Hahaha, your statement may be valid and u ain't contribute anything to this font even if you been seen problems with it. Doing intellectual masturbation on open source font, using edgy words to sound powerful. Why do you even spend time doing this lengthy critique kiddo 🤪

**Closed** 2024-01-18 04:32 UTC
